name:                htransaction
version:             0.1.0.0
github:              "githubuser/htransaction"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/htransaction#readme>

dependencies:
- base >= 4.7 && < 5
- polysemy
- containers
- aeson
- optparse-generic
- time
- bytestring
- polysemy-plugin
- cassava
- filepath
- req
- lens
- tagged
- text
- http-client
- http-types
- hspec
- hspec-discover
- rainbow
- co-log-polysemy
- random
- aeson-pretty

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -fplugin=Polysemy.Plugin
    - -Weverything
    - -Wno-missing-exported-signatures
    - -Wno-missing-import-lists
    - -Wno-missed-specialisations
    - -Wno-all-missed-specialisations
    - -Wno-unsafe
    - -Wno-safe
    - -Wno-missing-local-signatures
    - -Wno-monomorphism-restriction
    - -Werror
  default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies
    - DerivingStrategies
    - DeriveAnyClass
    - RecordWildCards
    - OverloadedStrings
    - GeneralizedNewtypeDeriving
    - DeriveGeneric
    - DeriveFunctor
executables:
  htransaction-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fplugin=Polysemy.Plugin
    - -Weverything
    - -Wno-missing-exported-signatures
    - -Wno-missing-import-lists
    - -Wno-missed-specialisations
    - -Wno-all-missed-specialisations
    - -Wno-unsafe
    - -Wno-safe
    - -Wno-missing-local-signatures
    - -Wno-monomorphism-restriction
    - -Werror
    dependencies:
    - htransaction
    default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies
    - DerivingStrategies
    - DeriveAnyClass
    - RecordWildCards
    - OverloadedStrings
    - GeneralizedNewtypeDeriving
    - DeriveGeneric
    - DeriveFunctor
tests:
  htransaction-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fplugin=Polysemy.Plugin
    - -Weverything
    - -Wno-missing-exported-signatures
    - -Wno-missing-import-lists
    - -Wno-missed-specialisations
    - -Wno-all-missed-specialisations
    - -Wno-unsafe
    - -Wno-safe
    - -Wno-missing-local-signatures
    - -Wno-monomorphism-restriction
    - -Werror
    dependencies:
    - htransaction

    default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies
    - DerivingStrategies
    - DeriveAnyClass
    - RecordWildCards
    - OverloadedStrings
    - GeneralizedNewtypeDeriving
    - DeriveGeneric
    - DeriveFunctor
